export const terms: Array <String> = [
    'Skilmálar vegna þátttöku í upptökum á samræðum og fyrirspurnum.',
    'Skilmálar voru uppfærðir 21.september 2020.',
    'Á vefsvæðinu [https://spjall.samromur.is/](www.spjall.samromur.is) getur þú tekið þátt í gerð Samræðu og fyrirspurna gagnasafnsins. Í þátttöku þinni felst að þú tekur upp samtalið þitt við annan þátttakenda og leggur eftir atvikum, til lýðfræðilegar upplýsingar. Með gerð gagnasafnsins verður hægt að styðja við og efla þróun máltæknilausna fyrir íslensku.',
    '1. Þátttaka í gerð gagnasafnsins',
    'Þú tekur þátt með því að taka upp spjall í gegnum vefsíðuna [https://spjall.samromur.is/](www.spjall.samromur.is). Gott er að lengd spjallsins sé á bilinu 15 til 30 mínútur. Spjallið verður ritað niður að samtali loknu. Markmið gagnasöfnunarinnar er að fá gögn um eðlilegt íslenskt talmál og því er mikilvægt að þátttakendur tali með eðlilegum hætti og reyna að forðast að notkun enskra orða.',
    'Sem þátttakandi samþykkir þú að öll þín framlög (raddupptaka, og eftir atvikum lýðfræðilegar upplýsingar) falli undir [https://creativecommons.org/licenses/by/4.0/](Creative Commons by attribution leyfi).',
    'Valkvætt er að skrá inn lýðfræðilegar upplýsingar, þ.e. aldursbil, kyn og notendanafn. Með því að skrá inn lýðfræðilega upplýsingar um þig staðfestir þú að þær séu skráðar af heilindum og séu sannar. Ósannar og rangar upplýsingar geta haft neikvæð áhrif á gagnasöfnunina.',
    'Þátttakendur þurfa að hafa náð 18 ára aldri og geta gefið upplýst samþykki fyrir þátttöku.',
    '2. Aðgengi að gagnasafni',
    'Gagnasafnið verður aðgengilegt í heild sinni með [https://creativecommons.org/licenses/by/4.0/](Creative Commons by attribution leyfi) á CLARIN.',
    '3. Persónuvernd',
    'Ef þú lætur í té framlag í formi samtals og eftir atvikum lýðfræðilegar upplýsingar kunna upplýsingarnar í einhverjum tilvikum að vera persónugreinanlegar. Í [persónuverndaryfirlýsingu Háskólans í Reykjavík](https://samromur.is/spjall/personuverndaryfirlysing) (HR) kemur fram hvernig HR nýtir persónugreinanlegar upplýsingar.',
    '6. Fyrirvari',
    'Háskólinn í Reykjavík er undanþeginn hvers kyns bótaábyrgð vegna notkunar gagnasafnsins sem er aðgengilegt öllum með [https://creativecommons.org/licenses/by/4.0/] (Creative Commons by attribution leyfi).',
    '7. Brot á skilmálum',
    'Ef upp kemst um brot þátttakenda á þessum skilmálum áskilur Háskólinn í Reykjavík sér rétt til að fjarlægja framlög viðkomandi þátttakanda úr gagnasafninu.',
    '8. Annað',
    'Hægt er að hafa samband við okkur í gegnum netfangið samromur@hr.is. Skilmálar Háskólans í Reykjavík eru endurskoðaðir reglulega og kunna því að taka breytingum. '
];
export const privacypol: Array<String> = [
    'Persónuverndaryfirlýsing Háskólans í Reykjavík',
    'Með persónuverndaryfirlýsingu þessari er greint frá því hvernig Háskólinn í Reykjavík ehf., kt. 510105-4190, Menntavegur 1, 102 Reykjavík (hér eftir „HR", „stofnunin" eða „við" ), stendur að vinnslu, s.s. söfnun, skráningu, vistun og miðlun persónugreinanlegra upplýsinga um einstaklinga (hér eftir einnig „ þú").',
    'Yfirlýsingin fjallar einkum um vinnslu persónuupplýsinga þegar einstaklingar: ',
    '• heimsækja vefinn, [https://spjall.samromur.is/](www.spjall.samromur.is). ',
    '• taka þátt í gerð Samræðu og fyrirspurna gagnasafnsins.',
    'HR vinnur persónuupplýsingar í samræmi við gildandi persónuverndarlöggjöf á Íslandi á hverjum tíma. Persónuverndaryfirlýsing þessi er byggð á lögum nr. 90/2018 um persónuvernd og vinnslu persónuupplýsinga („persónuverndarlög").',
    'Persónuvernd er HR mikilvæg',
    'Öflug persónuvernd er HR kappsmál og leggjum við mikla áherslu á að virða réttindi einstaklinga og að öll meðferð persónuupplýsinga sé ávallt í samræmi við gildandi regluverk á hverjum tíma, sem og í samræmi við bestu venjur á sviði máltækni.',
    'Hvaða persónuupplýsingum safnar HR um þig og hver er tilgangurinn með söfnuninni?',
    'HR leggur áherslu á að vinna einungis þær persónuupplýsingar sem nauðsynlegar eru í samræmi við þann tilgang sem liggur að baki söfnun upplýsinganna. HR vinnur persónuupplýsingar ekki frekar í óskyldum tilgangi nema einstaklingi sé tilkynnt um slíkt og þá heimild sem vinnslan byggir á. HR safnar, eins og við á hverju sinni, einkum eftirfarandi persónuupplýsingum: ',
    '• raddupptökum',
    '• lýðfræðilegum upplýsingum s.s. aldur, kyn, og notendanafni.',
    '• samskiptaupplýsingum, s.s. tölvupósti ',
    '• stafrænum fótsporum, s.s. nethegðun ',
    'HR vinnur persónuupplýsingar einkum í þeim tilgangi að: ',
    '• búa til opið íslenskt samræðu og fyrirspurnar gagnasafns til að styðja við og efla rannsóknir og þróun máltæknilausna fyrir íslensku.',
    'Þegar þú notar vefinn [https://spjall.samromur.is/](www.spjall.samrómur.is) söfnum við upplýsingum um notkun þína, þ.e. IP tölu, tegund eða útgáfu vafra sem þú notar, tímasetningu og tímalengd heimsóknar og hvaða undirsíður þú heimsækir innan vef Samróms. Hér má finna nánari upplýsingar um notkun okkar á vafrakökum (e. cookies), [samrómur.is/vafrakökustefna](https://www.samromur.is/vafrakokustefna).',
    'Lagalegur grundvöllur fyrir vinnslu',
    'HR safnar og vinnur persónuupplýsingar byggt á heimild í 6. tl. 1. mgr. 9. gr. persónuverndarlaga, þ.e. vegna lögmætra hagsmuna stofnunarinnar. Eftir atvikum kann HR einnig að vinna persónuupplýsingar byggt á samþykki þínu, sbr. 1. tl.1. mgr. 9. gr. persónuverndarlaga, s.s. ef þú skráir þig á póstlista okkar.',
    'Máltækni miðar að því að þróa búnað sem getur unnið með og skilið tungumál og stuðlar að notkun þeirra í samskiptum manns og tölvu. HR stuðlar að aðgengi almennings að íslensku raddgagnasafni til að styðja við og efla aðila sem vinna að þróun íslenskra máltæknilausna.',
    'Gagnasafnið er mikilvægt skref til að tryggja framtíð íslenskunnar og þar með menningu okkar. Nauðsynlegt er að tryggja að íslenskan standi jafnfætis öðrum tungumálum í síbreytilegum og hröðum tækniheimi og nýttir séu sem flestir möguleikar á hagnýtingu máltækni í nútíma samfélagi.',
    'Til að greiða fyrir gerð fullkomins raddgagnasafns eru þátttakendur beðnir um að gefa upp upplýsingar um aldur, kyn og notendanafn. Þessar upplýsingar bæta gæði samræðu og fyrirspurnar gagnasafnsins og eru liður í því að tryggja að gagnasafnið endurspegli sem flesta hópa samfélagsins.',
    'HR leggur sitt af mörkum til að tryggja að íslenskan glatist ekki með því að gera íslenskt samræðu og fyrirspurnar gagnasafn sem er í stöðugri þróun aðgengilegt öllum í ótakmarkaðan tíma. Samtalið og upplýsingarnar verða einungis notaðar til þess að skapa þekkingu á þessu mikilvæga sviði. Verkefnið er unnið í almannaþágu svo að framtíðin hljómi vel á íslensku.',
    'Hversu lengi geymum við persónuupplýsingar um þig?',
    'HR geymir persónuupplýsingar í þann tíma sem nauðsynlegur er til að uppfylla tilgang vinnslunnar eins og greint er frá honum hér að ofan.',
    'Frá hverjum safnar HR þínum persónuupplýsingum?',
    'Við söfnum persónuupplýsingum aðeins frá þér.',
    'Hvenær miðlar HR persónuupplýsingum þínum til þriðju aðila og af hverju?',
    'HR selur ekki undir neinum kringumstæðum persónuupplýsingar um þig. Samrómur er opið gagnasafn og hver sem er getur sótt upptökur og lýðfræðilegar upplýsingar. Mögulegt er því að miðlun persónuupplýsinga geti átt sér stað enda er tilgangurinn með söfnun upplýsinganna að stuðla að aðgengi almennings að gagnasafni með íslenskum röddum til að hægt sé að styðja við og efla aðila sem vinna að þróun íslenskra máltæknilausna.',
    'HR miðlar einungis persónuupplýsingum til þriðju aðila sem sækja sérstaklega raddgagnasafnið á vef [https://samromur.is/gagnasafn]Samróms. Mögulegt er að þriðju aðilar sem sækja gagnasafnið vinni gögnin í öðrum tilgangi. Persónuverndaryfirlýsing HR nær ekki til upplýsinga eða vinnslu þriðju aðila en við höfum enga stjórn né berum ábyrgð á notkun, birtingu eða öðrum verkum þeirra.',
    'Öryggi persónuupplýsinga og tilkynning um öryggisbrot',
    'Öryggi í vinnslu persónuupplýsinga er HR mikilvægt og höfum við gripið til viðeigandi tæknilegra og skipulagslegra öryggisráðstafana til að tryggja vernd persónuupplýsinga þinna. Þessum ráðstöfunum er ætlað að vernda persónuupplýsingar gegn því að þær glatist eða breytist fyrir slysni og gegn óleyfilegum aðgangi, afritun, notkun eða miðlun þeirra. Komi upp öryggisbrot er varðar þínar persónuupplýsingar munum við bregðast við í samræmi við persónuverndarlög.',
    'Réttindi þín',
    'Með fyrirvara um þau skilyrði sem nánar er fjallað um í gildandi löggjöf um persónuvernd, þá átt þú rétt á að: ',
    '• fá upplýsingar um hvaða persónuupplýsingar stofnunin hefur skráð um þig og uppruna þeirra, sem og upplýsingar um hvernig unnið er með persónuupplýsingar um þig, ',
    '• fá aðgang að þeim persónuupplýsingum sem eru unnar um þig, eða óska eftir að þær séu sendar til þriðja aðila, ',
    '• persónuupplýsingar þínar séu uppfærðar og leiðréttar ef tilefni er til, ',
    '• HR eyði persónuupplýsingum þínum ef ekki er málefnaleg eða lagaleg heimild til að varðveita þær, ',
    '• afturkalla samþykki þitt til vinnslu persónuupplýsinga, ef vinnsla byggir á slíku samþykki,',
    '• koma á framfæri andmælum ef þú vilt takmarka eða koma í veg fyrir að persónuupplýsingar þínar séu unnar, ',
    '• fá upplýsingar um það hvort fram fari sjálfvirk ákvarðanataka, á hvaða rökum slík ákvarðanataka er byggð og endurskoðun á sjálfvirkri ákvarðanatöku.',
    'Viljir þú nýta rétt þinn getur þú sent skriflega fyrirspurn á samromur@ru.is. Við munum staðfesta móttöku á beiðninni og að jafnaði bregðast við beiðnum innan mánaðar frá móttöku. Verði ekki unnt að bregðast við innan mánaðar munum við tilkynna þér um töf á afgreiðslu innan mánaðar. Ekki er innheimt gjald þegar einstaklingar nýta rétt sinn í samræmi við ofangreint.',
    'Þú hefur einnig rétt til að leggja fram kvörtun hjá Persónuvernd sjáir þú ástæðu til þess. Upplýsingar um persónuvernd má finna á heimasíðu þeirra, [https://www.personuvernd.is/] www.personuvernd.is.',
    'Frekari upplýsingar',
    'Ef þú vilt fá frekari upplýsingar um málefni sem snúa að þínum persónuupplýsingum þá bendum við þér á að hafa samband við Mál- og raddtæknistofu Gervigreindarseturs HR.',
    'Háskólinn í Reykjavík ehf. Menntavegur 1, 102 Reykjavík, sími: 599 6200, samromur@ru.is.',
    'Yfirferð og endurskoðun persónuverndaryfirlýsingar HR',
    'Persónuverndaryfirlýsing HR er endurskoðuð reglulega og uppfærð ef tilefni er til. Allar breytingar sem kunna að verða gerðar taka gildi eftir að uppfærð útgáfa hefur verið birt á heimasíðu Samróms.',
    'Þessi persónuverndaryfirlýsing var sett þann 12.10.2020.'
];
