export const talkingpoints = [
    'Hvað er málið með þetta veður?',
    'Hvað eldaðir þú í matinn í gær?',
    'Hvað segiru, alltaf í boltanum?',
    'Hvað eldar þú þegar þú ert að reyna gera vel við þig og þína?',
    'Hver er uppáhalds sundlaugin þín?',
    'Hvert fórst þú síðast þegar þú varst að ferðast innanlands?',
    'Hvað finnst þér best við að það búa þar sem þú býrð?',
    'Er langt síðan þú fórst í bíó?',
    'Myndir þú kaupa sjálfkeyrandi bíl?',
    'Hver er uppáhalds bíómyndin þín?',
    'Hvað er uppáhalds listaverkið þitt?',
    'Hvert myndir þú fara ef þú gætir farið hvert sem er?',
    'Hefur þú lesið einhverjar skemmtilegar greinar undanfarið?',
    'Hversu oft ferð þú út að hreyfa þig?',
    'Hver er uppáhalds árstíðin þín og af hverju?',
    'Hvernig heldur þú að heimurinn verði eftir 100 ár?',
    'Hvar sérð þú þig eftir 5 ár?',
    'Trúir þú á álfa, tröll eða drauga?',
    'Hver er uppáhalds liturinn þinn og af hverju?',
    'Hvaða pláneta er mest þú í sólkerfinu okkar?',
];
